# Generated by Django 4.2.23 on 2025-07-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='share_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
