# Generated by Django 4.2.23 on 2025-07-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_file_share_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='share_link',
        ),
        migrations.AddField(
            model_name='file',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
