# Generated by Django 4.2.23 on 2025-07-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_file_share_link_file_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='storage_name',
            field=models.CharField(default='storage_path', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
