# Generated by Django 4.2.23 on 2025-07-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile_storage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='storage_name',
            field=models.CharField(max_length=128),
        ),
    ]
