# Generated by Django 4.2.23 on 2025-07-17 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_userprofile_storage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='storage_name',
            new_name='storagename',
        ),
    ]
