# Generated by Django 4.2.23 on 2025-07-17 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_storage_name_userprofile_storagename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='storagename',
            new_name='storage',
        ),
    ]
