# Generated by Django 4.2.23 on 2025-07-17 04:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_storagename_userprofile_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='storage',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
