# Generated by Django 4.2.23 on 2025-07-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_file_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='share',
        ),
        migrations.AddField(
            model_name='file',
            name='filepath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='last_downloaded',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='file',
            name='share_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
