# Generated by Django 4.2.23 on 2025-08-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_userprofile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
