# Generated by Django 4.2.23 on 2025-08-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_userprofile_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='byte_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
