# Generated by Django 4.2.23 on 2025-08-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_file_byte_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='last_downloaded',
            field=models.DateTimeField(),
        ),
    ]
