# Generated by Django 4.2.23 on 2025-08-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_file_last_downloaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='last_downloaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
